### ISSUE TITLE
Boxes extending in right margin with v0.5 (TeX Live 2019)

### ISSUE THREAD

**Issue by vigou3** [milouse/latex-awesomebox#11]
Starting with v0.5 shipping with TeX Live 2019, awesomeboxes extend in the right margin. Here's a MWE:

```
\documentclass{article}
  \usepackage{mwe}
  \usepackage{awesomebox}

\begin{document}

\lipsum[1][1-3]
\notebox{\lipsum[2][1-3]}
\lipsum[3][1-3]

\end{document}
```

Compiling with 

```
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019)
```

yields

<img width="387" alt="Capture d’écran, le 2019-07-03 à 16 22 51" src="https://user-images.githubusercontent.com/18180682/60622675-dd0d0880-9dae-11e9-8e9b-f6d86aa3664b.png">

**Comment by milouse** [comment]
The problem comes from the underlying tabular cells definition. As you can see bellow, whatever margin you use, the array content will be always the same (note the difference between my first and last paragraph, and the fact that the box is always the same).

![Capture du 2019-07-04 09-15-00](https://user-images.githubusercontent.com/349239/60646688-4129de00-9e3c-11e9-98f5-eaa1206de9a2.png)

With the v0.5 we introduce a new customizable length `\aweboxcontentwidth` which is by default set as `\setlength{\aweboxcontentwidth}{0.92\linewidth}` (as described in the section 6.2 of the manual). For various reason we had to switch from tabularx to tabular and thus… no more `x`. In your case, 0.87 seems to do the job:

```latex
\documentclass{article}
\usepackage{mwe}
\usepackage{awesomebox}

\setlength{\aweboxcontentwidth}{0.87\linewidth}

\begin{document}

\lipsum[1][1-3]

\notebox{\lipsum[2][1-4]}

\lipsum[3][1-3]

\end{document}
```

![Capture du 2019-07-04 09-28-27](https://user-images.githubusercontent.com/349239/60647470-18a2e380-9e3e-11e9-8005-1c9a6e8f7c04.png)

**Comment by vigou3** [comment]
Merci Étienne.

I had read the manual and looked at the source code of the package. After investigating further, I now understand why the boxes extend in the right margin by default (as my MWE shows). 

The default columns widths are set to `0.08\linewidth` and `0.92\linewidth`, which appears to make sense since this totals `\linewidth`. However, this does not take into account the inter-column space and the rule width. Add all these lengths and you find the amount by which the box/table extends in the margin.

The difficulty, then, is in finding the correct `\aweboxcontentwidth` that will yield a table of exactly `\linewidth`. This is precisely what **tabularx** is good at. 

It shouldn't be up to the user to find this length. IMO, the current implementation is not satisfactory and the issue should remain open.

**Comment by vigou3** [comment]
Replacing `p{\aweboxcontentwidth}` in the table definitions by `p{\dimexpr\aweboxcontentwidth-#4-3\tabcolsep}` solves the issue.

Of course, the documentation would need to be adjusted accordingly, since `\aweboxcontentwidth` would now be the content width **less** the space needed to fit the box in a space of width `\aweboxleftmargin + \aweboxcontentwidth`.

**Comment by milouse** [comment]
Hi!

Thank you for your investigations and explanations. I had problems with tabularx and environment creation, and on the other hand and wanted to stay the more homogeneous between simple command and environment implementation. That's why I remove tabularx.

I'll check your proposal later this week and if it's work I'll published them. Until then, I agree this issue should stay open.

**Comment by georgerbr** [comment]
I've run into this too and experimented with `\aweboxcontentwidth` until I found an adequate value. @vigou3's solution is effective and elegant.

**Comment by milouse** [comment]
Hi all, sorry for being late, I've been busy. I just check your proposal @vigou3 and it seems ok for me. But I must admit I'm not a latex expert and before committing my changes, I would like to understand what I'm doing. Can you confirm that your command `\dimexpr\aweboxcontentwidth-#4-3\tabcolsep` should be read as this:

*Compute* (`\dimexpr`): `\aweboxcontentwidth` **minus** *fourth parameter* (`vrulewidth`) **minus** *3 × table cell padding* (`\tabcolsep`)

If it's ok, I'm wondering why you multiply `\tabcolsep` by 3 and not 4 ? For me the awesome box should look like:

```
|<---------------------------------- linewidth ----------------------------------->|
|<--------aweboxleftmargin (0.08)-------><--------aweboxcontentwidth (0.92)------->|
|<tabcolsep><aweboxleftmargin><tabcolsep><borderwidth><tabcolsep><--X--><tabcolsep>|
```

But currently we have:

```
|<tabcolsep><aweboxleftmargin><tabcolsep><borderwidth><tabcolsep><--X--><tabcolsep>|
|<aweboxleftmargin><borderwidth><tabcolsep><tabcolsep><tabcolsep><tabcolsep><--X-->|
|<aweboxleftmargin><------------------aweboxcontentwidth (0.92)------------------->|
```

Thus, `X = aweboxcontentwidth - (4 × tabcolsep + borderwidth)`

----

After some thought, I purpose to do the following. Replacing the line:

```latex
{p{\aweboxleftmargin}!{\color{#1}\vrule width #4}p{\aweboxcontentwidth}}
```

by

```latex
{p{\dimexpr\aweboxleftmargin-#4-2\tabcolsep}!{\color{#1}\vrule width #4}%
 p{\dimexpr\aweboxcontentwidth-2\tabcolsep}}
```

With the following default values:

```latex
\setlength{\aweboxleftmargin}{0.12\linewidth}
\setlength{\aweboxcontentwidth}{0.88\linewidth}
```

The **new** semantic is that both `\aweboxleftmargin` and `\aweboxcontentwidth` are the size of the boxe component *including the cell paddings* and that the border width is integrated in the *left margin* component. Or the following schema:

```
|<---------------------------------- linewidth ----------------------------------->|
|<-------------aweboxleftmargin (0.12)---------------><-aweboxcontentwidth (0.88)->|
|<tabcolsep><aweboxleftmargin><tabcolsep><borderwidth><tabcolsep><--X--><tabcolsep>|
```

Do you agree that?

**Comment by vigou3** [comment]
You're correct about the interpretation of the command: `\dimexpr` computes a length.

I don't recall exactly why a put `3\tabcolsep` instead of `4\tabcolsep`. Probably trial and error. :-) Now that a look at it again closely, it still wasn't 100% correct.

Personally, I would like the right side of awesomeboxes to be aligned on the right margin of text. That is: no padding or anything in the table cell. Your proposed solution does not achieve this in my tests.

I think it would be simpler to remove padding on the left of the first cell and on the right of the second cell, like this:

```
{@{}p{\dimexpr\aweboxleftmargin-\tabcolsep}!{\color{#1}\vrule width #4}%
       p{\dimexpr\aweboxcontentwidth-#4-\tabcolsep}@{}}
```

One rationale (other than cosmetic): users should not have to know that the box in set up in a tabular and, therefore, that is normal to have an indent of `\tabcolsep` on the left and on right. 

One could prefer that the box symbol be centered in the left cell. I don't have a strong opinion one way or another, but I probably prefer the centered version. To center the symbol, we should use instead as tabular declaration:

```
{@{}>{\centering\arraybackslash}%
 p{\dimexpr\aweboxleftmargin-\tabcolsep}!{\color{#1}\vrule width #4}%
 p{\dimexpr\aweboxcontentwidth-#4-\tabcolsep}@{}}
```

P.S. Don't forget to make the changes also in the environment API.

**Comment by georgerbr** [comment]
> P.S. Don't forget to make the changes also in the environment API.

How about a pull request so that we may review your proposed changes?

**Comment by milouse** [comment]
Hi all, I just pushed some new commit addressing this issue. Can you try this new version and check if it's ok for you?

I take the liberty to change the old `\aweboxleftmargin` and `\aweboxcontentwidth` behavior: instead of having dimension, we now just have variable (defined or customized with `\def`. That's because even with the proposed changed, as \aweboxleftmargin was computed once for all at the beginning of the document, we still have overflow in list environment, minipage or elsewhere. With this change (number instead of dimension) we are sure the generated boxes will always keep to the current `\linewidth`.

Even if I don't make a PR (sorry @georgerbr I only see your comment now :/ ), I'm still open to review and comment :)

**Comment by vigou3** [comment]
Good catch the fact that `aweboxleftmargin` and `aweboxcontentwidth` would be computed once and used throughout the document, generating overfull hboxes if the awesomebox is used inside another environment!

However, I don't think the proposed interface is a good choice for two reasons:

1. it is quite unusual in LaTeX to define parameters as merely fractional values;
2. even not so long ago, I was very reluctant (afraid?) as a LaTeX user to use plain TeX primitives like `\def`.

My proposal would rather be to add two more (!) optional parameters to `\awesomebox` to control what I'd call `iconwidth` (instead of `leftmargin`) and `contentwidth`, with default values `0.12\linewidth` and `0.88\linewidth`, respectively. That way, these values are computed each time a box is constructed and the widths adapt to the surrounding environment.

The declaration of the command would go as follows:

```
% \awesomebox[vrulecolor][hrule][title][iconwidth][contentwidth]{vrulewidth}{icon}{iconcolor}{content}
\NewDocumentCommand \awesomebox { O{abvrulecolor} O{} o O{0.12\linewidth} O{0.88\linewidth} m m m +m }{%
```

The numbering of arguments with a value > #4 in the definition need to be adjusted accordingly. Tested here with a hacked version of awesomebox.sty and it works A1.

**Comment by milouse** [comment]
I'm not very fund of infinite arguments. After some researches, I revert some of my changes to stick with the old API. `\aweboxleftmargin` and `\aweboxcontentwidth` are now expected to be expressed as a "best case scenario" (plain page) length. After that, each time a box is built, I just test if the current linewidth is the same than the reference one and adapt `\aweboxcontentwidth` accordingly for this box. I now provide a `test.tex` document in this repository to check various box situations.

Furthermore, I found some incompatibility with package such as geometry. To avoid problem, `\aweboxleftmargin` and `\aweboxcontentwidth` are now computed in a `\AtBeginDocument` block and thus their customization are expected to take place only after `\begin{document}`.

I think my last commits answer definitely this issue. Is it ok for you too?

**Comment by georgerbr** [comment]
Looks great!

Just replace "thiner" with "thinner" in https://github.com/milouse/latex-awesomebox/blob/d5849b29715fcbfc423b4b335dbacd11da726700/awesomebox.tex#L432

**Comment by vigou3** [comment]
Well, to paraphrase Spiderman: «with great control comes great number of arguments». :-D

The current version overflows in the right margin. Compiling `test.tex`with either with either pdftex of xetex yields, e.g.:

```
Overfull \hbox (2.22pt too wide) in paragraph at lines 17--17
```

I observed the same thing with my own test file. Loading geometry or not makes no difference.

**Comment by milouse** [comment]
That was mainly cause by the lorem package and latin words, which are badly hyphenated. I add `\usepackage[latin]{babel}` to mitigate it a little. The other little cause was whitespace left in command definitions.

Test and doc now compile without such warnings.

**Comment by vigou3** [comment]
I confirm that everything looks fine.

Merci Étienne!

**Comment by georgerbr** [comment]
Great!

In case anyone is interested in using the package with Overleaf -- at the moment [they use TeX Live 2016](https://www.overleaf.com/learn/how-to/What_packages_do_you_support%3F) and don't have the `fontawesome5` package but do have `fontawesome` --, I've attached the `.sty` file I use for my personal project.
[awesomebox-tl16.zip](https://github.com/milouse/latex-awesomebox/files/3438307/awesomebox-tl16.zip)

**Comment by milouse** [comment]
Thank you very much for your reviews. I'll tag and release the new version ASAP.

@georgerbr it's a really good idea. I've copied your .sty file in that repository as a new package `awesomebox-compat` and write about it in the README and the doc/test document.
