### ISSUE TITLE
Add option for RTL languages

### ISSUE THREAD

**Issue by ali4heydari** [milouse/latex-awesomebox#13]
Hi
It would be great to add an option for RTL languages. That means icon and vertical line goes to right and text goes left of vertical line.
thanks!

**Comment by milouse** [comment]
Hi, can you give me a minimal exemple document to help me work on it? The interesting part for me is how you configure the rest of your documents (with `babel`, `geometry`?).

Thank you very much!

**Comment by ali4heydari** [comment]
I noticed there was a problem and apparently it was from my file. I apologize for opening the invalid issue.
The minimal file below is where your package works well for right-to-left and left-to-right environments:
```tex
\documentclass[a4paper]{article}

\usepackage{awesomebox}
\usepackage{xepersian} % for writing Persian text

\settextfont{Arial} % XePersian command for setting document main font
\begin{document}
  \notebox{
    این یک متن نمونه است.
  }

  \begin{latin}
    \notebox{
      This is sample text.
    }
  \end{latin}
\end{document}
```

result:
![image](https://user-images.githubusercontent.com/29185622/62542366-e2a7b380-b870-11e9-9698-078bf1f5a6df.png)
Thanks!

**Comment by milouse** [comment]
Glad to hear it work for you :) Thanks for the example, it may help another time.
