### ISSUE TITLE
Support Variable Icon Sizes

### ISSUE THREAD

**Issue by dragonstyle** [milouse/latex-awesomebox#18]
Thanks for creating Awesomebox - it produces wonderful admonitions! Currently, the icon is always displaying using `\Huge` which looks good by default, but it would be very nice to be able to specify other sizes for the icon (.e.g. `\large`). Appreciate your work on this and your consideration for this feature request!

**Comment by georgerbr** [comment]
Try supplying the desired size directly into the `icon` argument of the `\awesomebox` command. The first example in subsection 5.1 changes from

``` tex
\awesomebox{5pt}{\faCertificate}{magenta}{Lorem ipsum…}
```

to

``` tex
\awesomebox{5pt}{\large{\faCertificate}{magenta}{Lorem ipsum…}
```

Just tested and it works.

**Comment by milouse** [comment]
Thanks for your help @georgerbr 

I think I can close this issue then.
