### ISSUE TITLE
Reliance on tabu that is currently in "emergency fix" mode causing problems

### ISSUE THREAD

**Issue by callegar** [milouse/latex-awesomebox#9]
Awesomebox currently relies on tabu, that unfortunately is now in "emergency fix mode". See https://github.com/tabu-fixed.  Until this is completed, tabu has various breakages.

One of tabu's current issues is some incompatibility with color/xcolor, on which awesomebox also relies. As a consequence, awesomebox may have strange and hard to diagnose failures.

In my case, a little patching of asesomebox to use tabularx instead of tabu was sufficient to work around the issue.  However, at this point it is not entirely clear to me if some features of tabu not present in tabularx are actually taken advantage of in awesomebox.  In case they are not, I suggest, moving to tabularx. Otherwise, I would suggest to make the possibility to use tabularx in place of tabu configurable.

**Comment by milouse** [comment]
After a quick search, `tabu` is required to allow the environment mode. `tabularx` does not seem to allow environment creation around a table cell.

On the other hand, [CTAN now points to tabu-fixed](https://www.ctan.org/pkg/tabu), thus various latex distribution will use this "emergency upgraded package".

So for now, without more exemple of major outage, I'll let this as backlog. Do not hesitate to provide a patch using only tabularx if you reach to make it works in `newenvironment` command.

Thank you very much.

**Comment by georgerbr** [comment]
Hi @callegar,
Please review so that @milouse can release 0.5.

**Comment by sergiocallegari** [comment]
Thanks for the reminder! I needed it since I had missed the note from Jan 30. I'll try to test as soon as I am back in office (in a couple of days).

**Comment by georgerbr** [comment]
Hi @sergiocallegari,
Please review and help @milouse release v0.5 with our contributions.

**Comment by milouse** [comment]
From my point of view, every thing is working as expected, thus I'll release it asap this week. @georgerbr please be patient :)

**Comment by georgerbr** [comment]
Thanks!

**Comment by sergiocallegari** [comment]
Sorry for not having been able to provide any input in time. I have resumed working today after having been ill and seen the evolution of the discussion just now. In any case, everything is fine with the fixed package for me too.
